# Generated by Django 5.0.3 on 2024-06-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.TextField()),
                ('cedula', models.TextField()),
                ('telefono', models.TextField()),
                ('correo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('cedula', models.TextField()),
                ('descripcion', models.TextField()),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='auto',
            name='velocidad',
            field=models.TextField(),
        ),
    ]
