# Generated by Django 5.0.3 on 2024-03-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('velocidad', models.FloatField()),
                ('placa', models.TextField()),
                ('color', models.TextField()),
            ],
        ),
    ]
